name: Build and Release Plugin

on:
  push:
    branches: [main]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install esbuild
        run: npm install -g esbuild

      - name: Read version from manifest.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' manifest.json)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build main.ts
        run: |
          mkdir -p helpers-plugin
          esbuild main.ts --bundle --platform=node --external:obsidian --outfile=helpers-plugin/main.js

      - name: Copy manifest and styles
        run: |
          cp manifest.json helpers-plugin/
          cp styles.css helpers-plugin/

      - name: Commit helpers-plugin folder to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add helpers-plugin
          git commit -m "Update helpers-plugin folder for v${{ steps.get_version.outputs.version }}" || echo "No changes to commit"
          git push

      - name: Zip helpers-plugin folder
        run: |
          cd helpers-plugin
          zip -r ../helpers-plugin.zip ./*
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          files: helpers-plugin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
