name: Build and Release Helpers Plugin

on:
  push:
    paths:
      - 'main.ts'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # required to publish release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install build tools
        run: npm install -g esbuild typescript

      - name: Fetch latest release tag
        id: get_release
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([0-9]+\.[0-9]+\.[0-9]+)".*/\1/')
          if [[ -z "$latest_tag" ]]; then
            echo "version=1.0.0" >> $GITHUB_OUTPUT
          else
            IFS='.' read -r major minor patch <<< "$latest_tag"
            patch=$((patch + 1))
            echo "version=${major}.${minor}.${patch}" >> $GITHUB_OUTPUT
          fi

      - name: Create plugin folder
        run: mkdir -p helpers-plugin

      - name: Compile TypeScript
        run: esbuild main.ts --bundle --platform=node --external:obsidian --outfile=helpers-plugin/main.js

      - name: Add manifest and styles
        run: |
          echo '{
            "id": "helpers-plugin",
            "name": "Helpers Plugin",
            "version": "${{ steps.get_release.outputs.version }}",
            "minAppVersion": "0.15.0",
            "description": "Reusable helper functions for Obsidian scripts",
            "author": "Your Name",
            "authorUrl": "",
            "isDesktopOnly": true
          }' > helpers-plugin/manifest.json

          echo '' > helpers-plugin/styles.css

      - name: Zip plugin folder
        run: zip -r helpers-plugin.zip helpers-plugin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Helpers Plugin v${{ steps.get_release.outputs.version }}
          tag_name: v${{ steps.get_release.outputs.version }}
          files: helpers-plugin.zip
